REM ***********************************************************************
REM THIS FILE IS CALLED FROM _BATCH.BAT FROM ALL FOLDERS THAT NEEDS AN AUTOGENERATED HTML FILE.
REM ***********************************************************************

REM Delayed Expansion is necessary for the string search script.
SETLOCAL EnableExtensions EnableDelayedExpansion

FOR /f "tokens=*" %%A in ('DIR /a-d /b') DO (
	if "!TESTFILE:;%%A;=!" EQU "!TESTFILE!" (
		@ECHO.%TAB%^<tr^>%WTF%
		REM FILE
		@ECHO.%TAB%%TAB%^<td^>%WTF%
		@ECHO.%TAB%%TAB%%TAB%^<a href="%DROPBOXLINK%"^>%%~nA^</a^>%WTF%
		@ECHO.%TAB%%TAB%^</td^>%WTF%
		REM LAST MODIFIED
		@ECHO.%TAB%%TAB%^<td^>%WTF%
		@ECHO.%TAB%%TAB%%TAB%%%~tA%WTF%
		@ECHO.%TAB%%TAB%^</td^>%WTF%
		REM FILE TYPE
		@ECHO.%TAB%%TAB%^<td^>%WTF%
		@ECHO.%TAB%%TAB%%TAB%%%~xA%WTF%
		@ECHO.%TAB%%TAB%^</td^>%WTF%
		REM FILE SIZE
		@ECHO.%TAB%%TAB%^<td^>%WTF%
		set /A "input=%%~zA/1024"
		CALL "%~dp0..\HEADER_FILES\_FUNCTIONS.bat" :showThousands input output
		@ECHO.%TAB%%TAB%%TAB% !output! kb %WTF%
		@ECHO.%TAB%%TAB%^</td^>%WTF%

		@ECHO.%TAB%^</tr^>%WTF%
	) else (
		@ECHO.
	)
)
